### ISSUE TITLE
OpenAM 12

### ISSUE THREAD

**Issue by laapsaap** [ConductAS/puppet-openam#1]
Hi,

Have this been tested with OpenAM 12?

**Comment by kimdane** [comment]
I don't think it has. But it will soon. Before the end of Mars we'll have an update.

—
Kim Daniel Engebretsen; +47 924 01 981; fax: +47 22 33 60 24
Kongens gate 14; Boks 805 Sentrum, 0104 Oslo;
http://www.conduct.no; mailto:kim@conduct.no

Conduct AS - Professional Open Source Services
- Red Hat/JBoss Premier System Integrator
- Puppet Labs System Integrator Partner
- Pentaho Preferred Integration Partner
- Atlassian Technology Partner
- Amazon Webservices Consulting Partner
- ForgeRock IAM & Security System Integrator Partner

**Comment by laapsaap** [comment]
That is a quick reply, thanks.

The company I work for runs OpenAM 10 and we are looking for experts to assist us with an upgrade to 12.  Can I contact you by email?

**Comment by kimdane** [comment]
Yes you can. But the administrative should go through my manager Jonas Olsson jonasso@conduct.no <mailto:jonasso@conduct.no>
as he has full overview of the available resources in my department.


—
Kim Daniel Engebretsen; +47 924 01 981; fax: +47 22 33 60 24
Kongens gate 14; Boks 805 Sentrum, 0104 Oslo;
http://www.conduct.no; mailto:kim@conduct.no

Conduct AS - Professional Open Source Services
- Red Hat/JBoss Premier System Integrator
- Puppet Labs System Integrator Partner
- Pentaho Preferred Integration Partner
- Atlassian Technology Partner
- Amazon Webservices Consulting Partner
- ForgeRock IAM & Security System Integrator Partner

**Comment by laapsaap** [comment]
I will send Jonas an email. Thank you.
